sudo: false
language: python
services:
- mongodb
python:
- '3.5'
- '3.4'
install:
- pip install coveralls
- pip install -r dev-requirements.txt
- pip install -r requirements.txt
before_script:
- flake8 .
script: py.test --cov=kalon
after_success:
- coveralls
